version: '2'

services:
    dev-server:
        image: node:9.1-slim
        volumes:
            - .:/opt/centriam-tiles
        ports:
            - '9000:9000'
        working_dir: /opt/centriam-tiles
        command: bash -c 'npm install && node_modules/.bin/webpack-dev-server --color --config webpack.dev-server.config.js'
